export const productos = [
  {
    id: 1,
    name: "Tapa blanca precintada - Modelo para frasco euro",
    image: "./images/1.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 2,
    name: "Tapa negra precintada - Modelo para frasco euro",
    image: "./images/2.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 3,
    name: "Spray dorado con tapa enfundada dorada - Modelo para frasco euro",
    image: "./images/3.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 4,
    name: "Tapa aluminio con inserto - Modelo para frasco euro",
    image: "./images/4.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 5,
    name: "Tapa enfundada dorada/plateada con inserto - Modelo para frasco euro",
    image: "./images/5.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 6,
    name: "Tapa ciega negra con inserto - Modelo para frasco euro",
    image: "./images/6.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 7,
    name: "Roll-on tapa negra - Modelo para frasco euro",
    image: "./images/7.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 8,
    name: "Spray con tapa negra - Modelo para frasco euro",
    image: "./images/8.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 9,
    name: "Frasco con tapa y tetina negra",
    image: "./images/9.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 728},
      {color: "Ambar", size: "15ML", price: 754},
      {color: "Ambar", size: "20ML", price: 806},
      {color: "Ambar", size: "30ML", price: 831},
      {color: "Ambar", size: "50ML", price: 936},
      {color: "Ambar", size: "100ML", price: 1040},
      {color: "Claro", size: "10ML", price: 806},
      {color: "Claro", size: "15ML", price: 831},
      {color: "Claro", size: "20ML", price: 859},
      {color: "Claro", size: "30ML", price: 923},
      {color: "Claro", size: "50ML", price: 1014},
      {color: "Claro", size: "100ML", price: 1092},
      {color: "Verde/Azul", size: "10ML", price: 871},
      {color: "Verde/Azul", size: "15ML", price: 910},
      {color: "Verde/Azul", size: "20ML", price: 962},
      {color: "Verde/Azul", size: "30ML", price: 1001},
      {color: "Verde/Azul", size: "50ML", price: 1104},
      {color: "Verde/Azul", size: "100ML", price: 1261},
    ],
  },
  {
    id: 13,
    name: "Frasco con tapa dorada y tetina blanca",
    image: "./images/13.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 17,
    name: "Frasco con tapa dorada",
    image: "./images/17.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 928},
      {color: "Ambar", size: "15ML", price: 954},
      {color: "Ambar", size: "20ML", price: 1006},
      {color: "Ambar", size: "30ML", price: 1031},
      {color: "Ambar", size: "50ML", price: 1136},
      {color: "Ambar", size: "100ML", price: 1240},
      {color: "Claro", size: "10ML", price: 1006},
      {color: "Claro", size: "15ML", price: 1031},
      {color: "Claro", size: "20ML", price: 1059},
      {color: "Claro", size: "30ML", price: 1123},
      {color: "Claro", size: "50ML", price: 1214},
      {color: "Claro", size: "100ML", price: 1292},
      {color: "Verde/Azul", size: "10ML", price: 1071},
      {color: "Verde/Azul", size: "15ML", price: 1110},
      {color: "Verde/Azul", size: "20ML", price: 1162},
      {color: "Verde/Azul", size: "30ML", price: 1201},
      {color: "Verde/Azul", size: "50ML", price: 1304},
      {color: "Verde/Azul", size: "100ML", price: 1461},
    ], 
  },
  {
    id: 23,
    name: "Frasco con tapa plata",
    image: "./images/23.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 928},
      {color: "Ambar", size: "15ML", price: 954},
      {color: "Ambar", size: "20ML", price: 1006},
      {color: "Ambar", size: "30ML", price: 1031},
      {color: "Ambar", size: "50ML", price: 1136},
      {color: "Ambar", size: "100ML", price: 1240},
      {color: "Claro", size: "10ML", price: 1006},
      {color: "Claro", size: "15ML", price: 1031},
      {color: "Claro", size: "20ML", price: 1059},
      {color: "Claro", size: "30ML", price: 1123},
      {color: "Claro", size: "50ML", price: 1214},
      {color: "Claro", size: "100ML", price: 1292},
      {color: "Verde/Azul", size: "10ML", price: 1071},
      {color: "Verde/Azul", size: "15ML", price: 1110},
      {color: "Verde/Azul", size: "20ML", price: 1162},
      {color: "Verde/Azul", size: "30ML", price: 1201},
      {color: "Verde/Azul", size: "50ML", price: 1304},
      {color: "Verde/Azul", size: "100ML", price: 1461},
    ], 
  },
  {
    id: 25,
    name: "Frasco con tapa ciega e inserto",
    image: "./images/25.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 648},
      {color: "Ambar", size: "15ML", price: 674},
      {color: "Ambar", size: "20ML", price: 726},
      {color: "Ambar", size: "30ML", price: 751},
      {color: "Ambar", size: "50ML", price: 856},
      {color: "Ambar", size: "100ML", price: 960},
      {color: "Claro", size: "10ML", price: 726},
      {color: "Claro", size: "15ML", price: 751},
      {color: "Claro", size: "20ML", price: 779},
      {color: "Claro", size: "30ML", price: 843},
      {color: "Claro", size: "50ML", price: 934},
      {color: "Claro", size: "100ML", price: 1012},
      {color: "Verde/Azul", size: "10ML", price: 791},
      {color: "Verde/Azul", size: "15ML", price: 830},
      {color: "Verde/Azul", size: "20ML", price: 882},
      {color: "Verde/Azul", size: "30ML", price: 921},
      {color: "Verde/Azul", size: "50ML", price: 1024},
      {color: "Verde/Azul", size: "100ML", price: 1181},
    ], 
  },
  {
    id: 29,
    name: "Frasco con tapa dorada y tetina blanca",
    image: "./images/29.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  },
  {
    id: 33,
    name: "Frasco con tapa blanca precintada",
    image: "./images/33.jpg",
    variants: [
      {color: "Ambar", size: "10ML", price: 0},
      {color: "Ambar", size: "15ML", price: 0},
      {color: "Ambar", size: "20ML", price: 0},
      {color: "Ambar", size: "30ML", price: 0},
      {color: "Ambar", size: "50ML", price: 0},
      {color: "Ambar", size: "100ML", price: 0},
      {color: "Claro", size: "10ML", price: 0},
      {color: "Claro", size: "15ML", price: 0},
      {color: "Claro", size: "20ML", price: 0},
      {color: "Claro", size: "30ML", price: 0},
      {color: "Claro", size: "50ML", price: 0},
      {color: "Claro", size: "100ML", price: 0},
      {color: "Verde/Azul", size: "10ML", price: 0},
      {color: "Verde/Azul", size: "15ML", price: 0},
      {color: "Verde/Azul", size: "20ML", price: 0},
      {color: "Verde/Azul", size: "30ML", price: 0},
      {color: "Verde/Azul", size: "50ML", price: 0},
      {color: "Verde/Azul", size: "100ML", price: 0},
    ], 
  }
];